# Recurring jobs configuration for Solid Queue

production:
  schedule_backups:
    class: ScheduleBackupsJob
    queue: scheduler
    schedule: every 15 minutes

  cleanup_deleted_files:
    class: CleanupDeletedFilesJob
    queue: backups
    schedule: every day at 3am

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

development:
  schedule_backups:
    class: ScheduleBackupsJob
    queue: scheduler
    schedule: every 5 minutes
